apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-ha.fullname" . }}-scripts
  labels:
    {{- include "postgres-ha.labels" . | nindent 4 }}
data:
  postgres-entrypoint.sh: |-
    {{- .Files.Get "scripts/postgres-entrypoint.sh" | nindent 4 }}
  pgpool-entrypoint.sh: |-
    {{- .Files.Get "scripts/pgpool-entrypoint.sh" | nindent 4 }}
