apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-ha.fullname" . }}-scripts
  labels:
    {{- include "postgres-ha.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    {{- .Files.Get "scripts/entrypoint.sh" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-ha.fullname" . }}-haproxy
  labels:
    {{- include "postgres-ha.labels" . | nindent 4 }}
data:
  haproxy.cfg: |-
    global
        maxconn 1000
    
    resolvers kube
        nameserver kube kube-dns.kube-system.svc.cluster.local:53
        hold timeout         600s
        hold refused         600s

    defaults
        log global
        mode tcp
        retries 2
        timeout client 30m
        timeout connect 4s
        timeout server 30m
        timeout check 5s
   
    listen health_check_http_url
        bind :8888
        mode http
        monitor-uri /healthz
        option      dontlognull

    frontend stats
        bind :8404
        stats enable
        stats uri /
        stats refresh 5s

    listen postgres_master
        bind *:5432
        mode tcp
        balance leastconn
        option httpchk
        option allbackups
        http-check expect status 200
        default-server port 9201 inter 3s downinter 5s slowstart 60s on-marked-down shutdown-sessions
        server-template postgres {{ .Values.replicaCount }} _postgres._tcp.{{ include "postgres-ha.fullname" . }}-headless.{{ .Release.Namespace }}.svc.cluster.local check init-addr none resolvers kube

