apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-ha.fullname" . }}
  labels:
    {{- include "postgres-ha.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.pgpool.type }}
  ports:
    - port: {{ .Values.service.pgpool.port }}
      targetPort: pgpool
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgres-ha.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-ha.fullname" . }}-headless
  labels:
    {{- include "postgres-ha.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.postgres.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgres-ha.selectorLabels" . | nindent 4 }}
