apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-ha.fullname" . }}
  labels:
    {{- include "postgres-ha.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "postgres-ha.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "postgres-ha.fullname" . }}-headless
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgres-ha.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgres-ha.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: postgres
          securityContext:
            {{- toYaml .Values.postgres.securityContext | nindent 12 }}
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          command:
            - /usr/bin/tini
          args:
            - /scripts/entrypoint.sh
          ports:
            - name: postgres
              containerPort: 15432
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - psql -p 15432 -w -c "SELECT 1"
            initialDelaySeconds: 15
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - psql -p 15432 -w -c "SELECT 1"
            initialDelaySeconds: 15
            timeoutSeconds: 2
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - pg_ctl -D "$PGDATA" -w stop
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresPassword | quote }}
            - name: REPMGR_PASSWORD
              value: {{ .Values.repmgrPassword | quote }}
            - name: HEADLESS_SERVICE
              value: {{ include "postgres-ha.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
            - name: scripts
              mountPath: /scripts
        - name: healthserver
          image: "{{ .Values.healthserver.image.repository }}:{{ .Values.healthserver.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.healthserver.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.healthserver.securityContext | nindent 12 }}
          ports:
            - name: healthserver
              containerPort: 9201
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 9201
            initialDelaySeconds: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9201
            initialDelaySeconds: 10
            periodSeconds: 3
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres@127.0.0.1:15432/postgres"
          resources:
            {{- toYaml .Values.healthserver.resources | nindent 12 }}
        - name: haproxy
          image: "{{ .Values.haproxy.image.repository }}:{{ .Values.haproxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.haproxy.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.haproxy.securityContext | nindent 12 }}
          ports:
            - name: haproxy
              containerPort: 5432
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 3
          resources:
            {{- toYaml .Values.haproxy.resources | nindent 12 }}
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "postgres-ha.fullname" . }}-scripts
            defaultMode: 0755
        - name: haproxy-config
          configMap:
            name: {{ include "postgres-ha.fullname" . }}-haproxy
            defaultMode: 0444
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- with .Values.postgres.storage.class }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
